### ISSUE TITLE
Mealie docker container fails to start due to apparent database issue

### ISSUE THREAD

**Issue by ih8gates** [mealie-recipes/mealie#3481]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I've been running Mealie for a few weeks in Docker on a Synology NAS running the hkotel:latest image. This morning, I made an update to a recipe and Mealie crashed. The container keeps crashing repeatedly. 

It looks like Watchtower updated the docker image I use last night, so it may be an issue caused by that update.

Is there a way that I can repair this without losing my recipes?

### Steps to Reproduce

Can't restart container.

### Please provide relevant logs

```INFO     2024-04-16T20:05:12 - Started server process [1]
INFO     2024-04-16T20:05:12 - Waiting for application startup.
INFO     2024-04-16T20:05:12 - start: database initialization
INFO     2024-04-16T20:05:12 - Database connection established.
INFO     2024-04-16T20:05:12 - Context impl SQLiteImpl.
INFO     2024-04-16T20:05:12 - Will assume non-transactional DDL.
INFO     2024-04-16T20:05:12 - Checking for migration data fixes
INFO     2024-04-16T20:05:13 - Updating recipe normalized search properties
ERROR    2024-04-16T20:05:13 - Error calling '<lambda>': local variable 'old_value' referenced before assignment
ERROR    2024-04-16T20:05:13 - Error calling '<lambda>': local variable 'old_value' referenced before assignment
ERROR    2024-04-16T20:05:13 - Error calling '<lambda>': This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: local variable 'old_value' referenced before assignment (Background on this error at: https://sqlalche.me/e/20/7s2a)
ERROR    2024-04-16T20:05:13 - Error calling '<lambda>': This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: local variable 'old_value' referenced before assignment (Background on this error at: https://sqlalche.me/e/20/7s2a)
ERROR    2024-04-16T20:05:13 - Error calling '<lambda>': This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: local variable 'old_value' referenced before assignment (Background on this error at: https://sqlalche.me/e/20/7s2a)
ERROR    2024-04-16T20:05:13 - Error calling '<lambda>': This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: local variable 'old_value' referenced before assignment (Background on this error at: https://sqlalche.me/e/20/7s2a)
ERROR    2024-04-16T20:05:13 - Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/app/mealie/app.py", line 60, in lifespan_fn
    init_db.main()
  File "/app/mealie/db/init_db.py", line 111, in main
    if db.users.get_all():
  File "/app/mealie/repos/repository_generic.py", line 90, in get_all
    results = self.page_all(pq, override=override)
  File "/app/mealie/repos/repository_generic.py", line 307, in page_all
    q, count, total_pages = self.add_pagination_to_query(q, pagination_result)
  File "/app/mealie/repos/repository_generic.py", line 345, in add_pagination_to_query
    count = self.session.scalar(count_query)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2354, in scalar
    return self._execute_internal(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2181, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2050, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
  File "<string>", line 2, in _connection_for_bind
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
    self._raise_for_prerequisite_state(fn.__name__, current_state)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 928, in _raise_for_prerequisite_state
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: local variable 'old_value' referenced before assignment (Background on this error at: https://sqlalche.me/e/20/7s2a)
ERROR    2024-04-16T20:05:13 - Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/app/mealie/app.py", line 60, in lifespan_fn
    init_db.main()
  File "/app/mealie/db/init_db.py", line 111, in main
    if db.users.get_all():
```

### Mealie Version

hkotel-mealie:latest 

### Deployment

Docker (Synology)

**Comment by c0by85** [comment]
Same problem here, workaround use the nightly version. Downgrading wont fix the problem.

```
mealieRC  | INFO     2024-04-17T15:09:57 - Started server process [1]
mealieRC  | INFO     2024-04-17T15:09:57 - Waiting for application startup.
mealieRC  | INFO     2024-04-17T15:09:57 - start: database initialization
mealieRC  | INFO     2024-04-17T15:09:57 - Database connection established.
mealieRC  | INFO     2024-04-17T15:09:57 - Context impl SQLiteImpl.
mealieRC  | INFO     2024-04-17T15:09:57 - Will assume non-transactional DDL.
mealieRC  | INFO     2024-04-17T15:09:57 - Checking for migration data fixes
mealieRC  | INFO     2024-04-17T15:09:58 - Updating recipe normalized search properties
mealieRC  | ERROR    2024-04-17T15:09:58 - Error calling '<lambda>': local variable 'old_value' referenced before assignment
mealieRC  | ERROR    2024-04-17T15:09:58 - Error calling '<lambda>': local variable 'old_value' referenced before assignment
mealieRC  | ERROR    2024-04-17T15:09:58 - Error calling '<lambda>': This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: local variable 'old_value' referenced before assignment (Background on this error at: https://sqlalche.me/e/20/7s2a)
mealieRC  | ERROR    2024-04-17T15:09:58 - Error calling '<lambda>': This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: local variable 'old_value' referenced before assignment (Background on this error at: https://sqlalche.me/e/20/7s2a)
mealieRC  | ERROR    2024-04-17T15:09:58 - Error calling '<lambda>': This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: local variable 'old_value' referenced before assignment (Background on this error at: https://sqlalche.me/e/20/7s2a)
mealieRC  | ERROR    2024-04-17T15:09:58 - Error calling '<lambda>': This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: local variable 'old_value' referenced before assignment (Background on this error at: https://sqlalche.me/e/20/7s2a)
mealieRC  | ERROR    2024-04-17T15:09:58 - Traceback (most recent call last):
mealieRC  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 732, in lifespan
mealieRC  |     async with self.lifespan_context(app) as maybe_state:
mealieRC  |   File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
mealieRC  |     return await anext(self.gen)
mealieRC  |   File "/app/mealie/app.py", line 60, in lifespan_fn
mealieRC  |     init_db.main()
mealieRC  |   File "/app/mealie/db/init_db.py", line 111, in main
mealieRC  |     if db.users.get_all():
mealieRC  |   File "/app/mealie/repos/repository_generic.py", line 90, in get_all
mealieRC  |     results = self.page_all(pq, override=override)
mealieRC  |   File "/app/mealie/repos/repository_generic.py", line 307, in page_all
mealieRC  |     q, count, total_pages = self.add_pagination_to_query(q, pagination_result)
mealieRC  |   File "/app/mealie/repos/repository_generic.py", line 345, in add_pagination_to_query
mealieRC  |     count = self.session.scalar(count_query)
mealieRC  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2354, in scalar
mealieRC  |     return self._execute_internal(
mealieRC  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2181, in _execute_internal
mealieRC  |     conn = self._connection_for_bind(bind)
mealieRC  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2050, in _connection_for_bind
mealieRC  |     return trans._connection_for_bind(engine, execution_options)
mealieRC  |   File "<string>", line 2, in _connection_for_bind
mealieRC  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
mealieRC  |     self._raise_for_prerequisite_state(fn.__name__, current_state)
mealieRC  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 928, in _raise_for_prerequisite_state
mealieRC  |     raise sa_exc.PendingRollbackError(
mealieRC  | sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: local variable 'old_value' referenced before assignment (Background on this error at: https://sqlalche.me/e/20/7s2a)
mealieRC  |
mealieRC  | ERROR    2024-04-17T15:09:58 - Application startup failed. Exiting.
mealieRC  | ERROR    2024-04-17T15:09:58 - Traceback (most recent call last):
mealieRC  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 732, in lifespan
mealieRC  |     async with self.lifespan_context(app) as maybe_state:
mealieRC  |   File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
mealieRC  |     return await anext(self.gen)
mealieRC  |   File "/app/mealie/app.py", line 60, in lifespan_fn
mealieRC  |     init_db.main()
mealieRC  |   File "/app/mealie/db/init_db.py", line 111, in main
mealieRC  |     if db.users.get_all():
mealieRC  |   File "/app/mealie/repos/repository_generic.py", line 90, in get_all
mealieRC  |     results = self.page_all(pq, override=override)
mealieRC  |   File "/app/mealie/repos/repository_generic.py", line 307, in page_all
mealieRC  |     q, count, total_pages = self.add_pagination_to_query(q, pagination_result)
mealieRC  |   File "/app/mealie/repos/repository_generic.py", line 345, in add_pagination_to_query
mealieRC  |     count = self.session.scalar(count_query)
mealieRC  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2354, in scalar
mealieRC  |     return self._execute_internal(
mealieRC  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2181, in _execute_internal
mealieRC  |     conn = self._connection_for_bind(bind)
mealieRC  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2050, in _connection_for_bind
mealieRC  |     return trans._connection_for_bind(engine, execution_options)
mealieRC  |   File "<string>", line 2, in _connection_for_bind
mealieRC  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
mealieRC  |     self._raise_for_prerequisite_state(fn.__name__, current_state)
mealieRC  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 928, in _raise_for_prerequisite_state
mealieRC  |     raise sa_exc.PendingRollbackError(
mealieRC  | sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: local variable 'old_value' referenced before assignment (Background on this error at: https://sqlalche.me/e/20/7s2a)
mealieRC  |
mealieRC  | ERROR    2024-04-17T15:09:58 - Application startup failed. Exiting.
mealieRC exited with code 0
```

**Comment by tba-code** [comment]
Please try the nightly build. I believe this was fixed yesterday by #3475 

I'd recommend excluding it from watchtower until a stable release fixes the issue.

**Comment by ih8gates** [comment]
Thanks. To make sure I understand the right way to do that (in Docker), I just make sure the container is stopped and download nightly from the registry... then how do I tell my container to use that downloaded image (and keep all of my containers config & data)?

Sorry - I know that I'm asking about how to use Docker here.

**Comment by c0by85** [comment]
edit your docker compose file.

```
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:nightly
#    image: ghcr.io/mealie-recipes/mealie:latest
```

and restart the container.

**Comment by tba-code** [comment]
> edit your docker compose file.
> 
> ```
> services:
>   mealie:
>     image: ghcr.io/mealie-recipes/mealie:nightly
> #    image: ghcr.io/mealie-recipes/mealie:latest
> ```
> 
> and restart the container.

Recreate the container, not restart it. The command (assuming you are using compose for this) is ```docker compose up -d``` assuming the compose file is named ```docker-compose.yml``` and you run the command from the same directory.

**Comment by ih8gates** [comment]
I'm doing everything via the Synology Docker GUI.

**Comment by michael-genson** [comment]
This should be fixed on the latest release, so you no longer need to switch to nightly. Try updating the image and seeing if that fixes it.

If you're not sure how to do that, assuming you're using Synology's Container Manager, can you confirm if you're using the Project or the Container tab for Mealie?

**Comment by c0by85** [comment]
> This should be fixed on the latest release, so you no longer need to switch to nightly. Try updating the image and seeing if that fixes it.
> 
> If you're not sure how to do that, assuming you're using Synology's Container Manager, can you confirm if you're using the Project or the Container tab for Mealie?

looks good, container starts again without errors. thx.

**Comment by ih8gates** [comment]
I'm using the Synology DSM GUI for Docker. It appears to pull the image [from here](https://registry.hub.docker.com/r/hkotel/mealie/). I re-downloaded the image (found in the Registry, right-click-download) then started the container. Still get the same error. 

I don't understand the ecosystem well enough to know how to tell that I'm getting the build that involves the fix, though. I suspect there's some lag although hkotel/mealie says it was updated 3 hours ago (1pm-ish Eastern). I'll wait and give it another try in a bit.

**Comment by michael-genson** [comment]
> I'm using the Synology DSM GUI for Docker

What is the name of the app? Depending on your DSM version you may be using the old Docker manager or the new Container Manager

**Comment by ih8gates** [comment]
> What is the name of the app?

Likely the old Docker manager. Not 100% sure how to tell. Package Center says that it's version 20.10.3-0554

**Comment by michael-genson** [comment]
Can you post a screenshot of the window?

**Comment by ih8gates** [comment]
Thanks for your patience. I checked this morning and am still unable to run Mealie after following the steps that I think update the image for the container. Here's the steps I'm completing:

1. Find hkotel/mealie in the registry.
2. Right-click on it and choose download, then choose "latest" tag.
3. Wait until DSM says that the image has downloaded.
4. Start the hkotel/mealie container

I'm still seeing the previous error in the container's log.

Is there a step between 3 and 4 that I'm missing? Do I need to do something to make the container use the newly downloaded image?

Screencap of my Docker GUI:

![docker](https://github.com/mealie-recipes/mealie/assets/22531017/9a10e8e2-2112-4448-9c6c-1b77785b8794)

**Comment by michael-genson** [comment]
Okay yep, that's the old docker app. I didn't realize that was still supported, but I think it has to do with DSM version. Doesn't matter for this, though

Did you mount your docker volume? It should be in the container settings somewhere if you mounted `/app/data` to a local volume. I ask because to update the image on a docker container you need to clean the container first, which effectively deletes all data that isn't mounted

**Comment by ih8gates** [comment]
If I understand your question correctly, yes - I have /app/data mapped to a folder outside of the container via "volume" settings on the container. I confirmed that this folder contains several folders (including "recipes" which contains a number of folders that looks to correspond correctly with the number of recipes I've created). I made a backup of that folder just in case. 

When I right-click on a container, my available options are start / reset / delete.

If I "delete" (and my mounted data is preserved), will that delete all of the config settings I've made the the environment of the container?

**Comment by michael-genson** [comment]
Great, in that case all you have to do is reset the container, then build it again (probably just by hitting start). Resetting cleans the image (i.e. removes it) and rebuilds it using the new latest image you just downloaded. All of the app's data and config settings are in your mounted data, so you won't lose anything.

**Comment by ih8gates** [comment]
Thanks. "Reset" sounded destructive, so it gave me pause. I reset the container and then started it and everything is now running properly! Thanks for the help!

**Comment by michael-genson** [comment]
Great! Glad to hear!
