### ISSUE TITLE
Entra ID - OpenID Connect - Groups Claim Error

### ISSUE THREAD

**Issue by KrzysztofKiser** [mealie-recipes/mealie#4528]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I am trying to set up an OpenID Connect SSO with Entra ID. 
All works well, until I add the required groups. 

The groups claim is added in Entra ID, however, Mealie is reporting that the claim is missing. 

![image](https://github.com/user-attachments/assets/2b72f9d3-0529-4219-930f-405078d162f9)

### Steps to Reproduce

1) Add OIDC_USER_GROUP and OIDC_ADMIN_GROUP as variables 
2) Try to use SSO
3) Error appears

### Please provide relevant logs

authlib.integrations.base_client.errors.OAuthError: invalid_client: AADSTS650053: The application 'Mealie SSO' asked for scope 'groups' that doesn't exist on the resource '00000003-0000-0000-c000-000000000000'. Contact the app vendor. Trace ID: 53ff2a6b-2fe2-43da-95d4-11017c5f2d00 Correlation ID: 7eb3636c-51bd-49a6-a6af-7521b18576f3 Timestamp: 2024-11-08 23:01:33Z

### Mealie Version

v2.1.0 

### Deployment

Docker (Linux)

**Comment by cmintey** [comment]
That error looks like it coming from Azure. Seems like the groups claim isn't properly configured there

**Comment by KrzysztofKiser** [comment]
There aren't really any settings for this in Azure and the problem is only with Mealie. 
![image](https://github.com/user-attachments/assets/87f9e7c7-a4b3-4f0d-8f46-09578bf8bbda)

I am using OpenID Connect with the same settings in other apps and it works just fine.

**Comment by cmintey** [comment]
I looked into it a bit and found that Entra doesn't have a `groups` scope that you can request and that a `groups` claim is always returned when you add in in the portal. Mealie is set up to request the `groups` scope when groups are used, so we'll have to add an additional setting to override that

**Comment by cmintey** [comment]
Added a new env var called `OIDC_SCOPES_OVERRIDE`, you can set this to `openid profile email` and this should resolve the issue. You can either wait for the next release or pull the nightly image

**Comment by KrzysztofKiser** [comment]
@cmintey - thank you very much for looking into this. 

I just downloaded the nightly release, added the `OIDC_SCOPES_OVERRIDE` variable and set it to `openid profile email` however it doesn't seem to resolve the issue. I keep getting the following error: 
`[OIDC] Required claims not present. Expected: {'name', 'groups', 'email'} Actual: dict_keys(['aud', 'iss', 'iat', 'nbf', 'exp', 'email', 'name', 'nonce', 'oid', 'preferred_username', 'rh', 'sub', 'tid', 'uti', 'ver'])`

**Comment by cmintey** [comment]
Make sure your Azure app configuration is configured to put the `groups` claim on the ID token

**Comment by KrzysztofKiser** [comment]
The groups claim is configured for the ID token in Azure
![image](https://github.com/user-attachments/assets/8b4aa129-8313-4370-b467-8ca8703e6cee)

**Comment by cmintey** [comment]
I use Azure for backups, so I set up a Mealie client in Azure to try it out and it is working for me. The `groups` claim is being returned using this configuration and is signing me in successfully.

**Comment by KrzysztofKiser** [comment]
I removed the app in Azure, added it again and it started working now. Not sure what the problem was, but it's working as expected now. 

Thank you again!

**Comment by cmintey** [comment]
Strange.. glad it works now!
