### ISSUE TITLE
[UX] - Dropdown menu isn't fixed

### ISSUE THREAD

**Issue by lemystere** [mealie-recipes/mealie#6546]
### First Check

- [x] This is not a feature request.
- [x] I added a very descriptive title to this issue (title field is above this).
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the Mealie documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

On the recipe scraper or on any recipe page, the dropdown menus used to select units or ingredients are not fixed.
The problem is minor on desktop, but on smartphones it becomes a real issue because the dropdown can “move away” when scrolling, making it difficult to interact with.

It's _possible_ that this behavior started in Mealie v3.2.0, but I haven't tested earlier versions to confirm.

### Steps to Reproduce

1) Open a recipe (or add a new one using the scraper).
2) Click on a dropdown to select units or ingredients.
3) Scroll down the page.
4) The dropdown behaves strangely and moves with the scroll.

=> On a smartphone, the issue is more noticeable and more problematic.

### Please provide relevant logs

On desktop : <img width="956" height="773" alt="Image" src="https://github.com/user-attachments/assets/4cdea848-309e-4c79-ad78-60f1eb2c4b3b" />

On smartphone :
<img width="603" height="1311" alt="Image" src="https://github.com/user-attachments/assets/f30765e7-0342-40fb-8bfc-2ba87e7d8417" />
<img width="603" height="1311" alt="Image" src="https://github.com/user-attachments/assets/0390acd7-81c9-40b4-a12b-459f555fbefd" />
<img width="603" height="1311" alt="Image" src="https://github.com/user-attachments/assets/9ae646f1-50ce-4833-9340-e4a7d5372e83" />

### Mealie Version

Mealie v3.5.0

### Deployment

Docker (Windows)

**Comment by lehnerpat** [comment]
I'm also seeing this on v3.8.0, and it's especially annoying on the shopping list page, where it affects the dropdowns for unit, food, and label.

In some cases the dropdown even moves _away_ from the field it should be attached to.

**Comment by pretubedongit** [comment]
I am seeing this on v3.9.1. Meal planner is not usable on Mobile due to the dropdown list issue. Also, intermittently selecting recipes converts to a random string, which does not allow me to add recipe to today's meal planner.

**Comment by lehnerpat** [comment]
Just wanted to share: the issues I'm seeing on the shopping list page seem to be caused by a bug in Vuetify's autocomplete component (I opened https://github.com/vuetifyjs/vuetify/issues/22490 for that). But I'm only seeing that specific behavior on iOS, not on desktop.

**Comment by mnoah66** [comment]
Experiencing the same frustrating issue on iOS. Makes meal planner unusable on mobile.

**Comment by DownByLaws** [comment]
Issue got worse since the new add item button in shopping lists moved to the bottom of the page for mobile. Makes it close to impossible to select an item from the dropdown menu now.

**Comment by michael-genson** [comment]
For shopping lists specifically this is fixed in nightly

**Comment by skyio1** [comment]
This is worse in the meal planner, basically unusable in iOS mobile due to the dropdown options appearing below the keyboard and you can't select one of them.

**Comment by Smith8154** [comment]
Yeah, I essentially can't use the meal planner on iOS. I start typing in the name of a recipe and the popup box is just nowhere to be found. Every time I want to use the meal planner, I have to get out my laptop.

**Comment by lehnerpat** [comment]
@michael-genson, unfortunately the latest release (3.18.0) didn't fix this for me in the shopping list either.

At least on my iPhone 13 mini, the dropdowns still appear way below where they should be. With the new "Add Item" area being shown at the bottom of the screen, this makes it almost impossible to select anything from dropdowns while adding new shopping list items manually on the phone. We're having to resort to using another device, or adding an item without selecting any food/unit/section, and then editing it (because the editing is shown further up on the screen, we have a chance of finding/hitting the dropdown)

**Comment by polo817** [comment]
This is still unusable on iOS Safari on the ingredient selection dropdown (during recipe parse editing). The dropdown stays hidden under the keyboard.

**Comment by michael-genson** [comment]
This seems fixed in 3.20.1, if after upgrading you're still experiencing this let me know and I'll re-open!

**Comment by polo817** [comment]
Fixed for me, thank you! @michael-genson
