### ISSUE TITLE
[v1.0.0b] - Some issues about users

### ISSUE THREAD

**Issue by gabt92** [mealie-recipes/mealie#815]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

1. Once a user is created, if we try to create another one right after, the form already have all the fields in error saying they are required.

![image](https://user-images.githubusercontent.com/38195308/142961035-1ce58c99-a3eb-42d9-b49c-d6b59aa56b26.png)

- [X] 2. Assigning no group the the Fileld Style (??) field will assign the first group, which is 'Home'. I'm not sure if it's what expected.
Seems like it is, found this in the doc. My bad.
![image](https://user-images.githubusercontent.com/38195308/143030227-a3d62cd1-82d7-4fa0-9266-e9c17c7f32f2.png)

3. Creating new groups seems to work since I can see them in the new user form but it's not possible to see them in the group page even if the data is returned.
![image](https://user-images.githubusercontent.com/38195308/142961258-0b2d56c4-0a2e-453f-9216-49ef800d1531.png)
![image](https://user-images.githubusercontent.com/38195308/142961306-44a4970d-a9e5-4077-a910-571213c6fa13.png)
![image](https://user-images.githubusercontent.com/38195308/142961325-aef63dbf-a714-4e3f-850c-4b34de3067cb.png)

4. When editing the user, if we change things like "administrator" and then select "cancel", the information still changes on the page. (But not sent to the backend so a refresh will fix this)

### Deployment

Other

### Deployment Details

Beta on https://beta.mealie.io/

**Comment by hay-kot** [comment]
> Once a user is created, if we try to create another one right after, the form already have all the fields in error saying they are required.

Should be resolved

> Assigning no group the the Fileld Style (??) field will assign the first group, which is 'Home'. I'm not sure if it's what expected.

Filled style has been fixed. Can't submit the form without selecting a group anymore. 

> When editing the user, if we change things like "administrator" and then select "cancel", the information still changes on the page. (But not sent to the backend so a refresh will fix this)

Should also be fixed.

---

Working on the group stuff in the next PR

**Comment by gabt92** [comment]
1. Yes, I don't have the issue anymore
2. Yes, I confirm that too
![image](https://user-images.githubusercontent.com/38195308/143294406-46d782aa-76f9-4476-a89b-68f184acc691.png)
3. Still in progress in you next PR I think.
4. Seems ok now. But editing is a little bit confusing in my opinion. When we select the user, we are apparently in "edit" mode and can change stuff.. But will still have the "create" button. The button is working as a "Edit" one, but I would change the name of it...
![image](https://user-images.githubusercontent.com/38195308/143294740-b46de852-fec0-4c6d-a050-14c9a9fd2cee.png)

**Comment by hay-kot** [comment]
> Still in progress in you next PR I think.

Correct, working on group stuff in the next round of PRs

> Seems ok now. But editing is a little bit confusing in my opinion. When we select the user, we are apparently in "edit" mode and can change stuff.. But will still have the "create" button. The button is working as a "Edit" one, but I would change the name of it...

Got a little trigger happy with the copy/paste. Fixed in the next PR

**Comment by hay-kot** [comment]
> Creating new groups seems to work since I can see them in the new user form but it's not possible to see them in the group page even if the data is returned.

and

> Seems ok now. But editing is a little bit confusing in my opinion. When we select the user, we are apparently in "edit" mode and can change stuff.. But will still have the "create" button. The button is working as a "Edit" one, but I would change the name of it...

Fixed in 

- PR #838
